name: Setup Node
description: Setting up Node.js with pnpm
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: '.node-version'
        cache: pnpm
        cache-dependency-path: 'pnpm-lock.yaml'
    - run: pnpm i
      shell: bash
