name: Checking config file of Renovate

on:
  pull_request:
    paths:
      - 'renovate.json'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setting up node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '22'

      - name: validating renovate config
        run: npx --package renovate -c 'renovate-config-validator'
