name: Checking code quality

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setting up Node.js
        uses: ./.github/actions/setup-node

      - name: npm install
        run: pnpm i

      - name: build
        run: pnpm run build

      - name: lint
        run: pnpm run lint

      - name: test
        run: pnpm run test:ci
