name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: validating renovate config
        run: npx --package renovate -c 'renovate-config-validator'

      - name: npm install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: |
          npm run test:ci
          npx codecov@3.0.2

      - name: build
        run: npm run build
